/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 22 10:03:48 GMT 2021
 */

package com.neu.Rohit.Exception;

import org.junit.Test;
import static org.junit.Assert.*;
import com.neu.Rohit.Exception.AddException;
import org.junit.runner.RunWith;

public class AddException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddException addException0 = new AddException("");
      AddException addException1 = new AddException("", addException0);
      assertFalse(addException1.equals((Object)addException0));
  }
}
